- id: '1750228235196'
  alias: tv off 11:59
  description: ''
  triggers:
  - trigger: time
    at: '23:59:00'
  conditions: []
  actions:
  - type: turn_off
    device_id: d6bcf1e95521d797b851f1b6a9d6c18b
    entity_id: 41d6d9ad5fda46d4d89c6843b816b2aa
    domain: remote
  mode: single

- id: turn_off_hallway_nest_when_upstairs_clients_disconnect
  alias: Turn off Hallway Nest when upstairs devices leave AP
  description: >
    If any of my four tracked devices are either off–network or
    no longer on the “U6_Pro_Master” UniFi access point, turn off
    the hallway Nest thermostat.
  trigger:
    - platform: state
      entity_id:
        - device_tracker.iphone
        - device_tracker.iphone_2
  condition:
    - condition: template
      value_template: >-
        {% set upstairs_ap = 'U6_Pro_Master' %}
        {% for dev in ['device_tracker.iphone','device_tracker.iphone_2'] %}
          {% if states(dev) != 'home' or state_attr(dev,'access_point') != upstairs_ap %}
            true
          {% endif %}
        {% endfor %}
        false
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.hallway
  mode: single
