default_config:

zeroconf:
  default_interface: true

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene:  !include scenes.yaml

template:
  - binary_sensor:
      - name: "Andrew iPhone on UniFi"
        unique_id: andrew_iphone_unifi
        device_class: connectivity
        state: >
          {{ state_attr('device_tracker.andrew_iphone','connected') }}
        availability: >
          {{ not is_state('device_tracker.andrew_iphone','unavailable') }}
