default_config:

zeroconf:
  default_interface: true

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene:  !include scenes.yaml

template:
  - binary_sensor:
      - name: "Andrew iPhone on UniFi"
        unique_id: andrew_iphone_online
        device_class: connectivity
        state: >-
          {{ state_attr('device_tracker.andrew_iphone', 'essid') == 'MBDTF' }}

template:
  - binary_sensor:
      - name: "Mike iPhone on UniFi"
        unique_id: mike_iphone_online
        device_class: connectivity
        state: >-
          {{ state_attr('device_tracker.mike_iphone', 'essid') == 'MBDTF' }}
