default_config:

zeroconf:
  default_interface: true

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene:  !include scenes.yaml

type: entities
entities:
  - entity: lock.yale_assure_2
    name: Front Door Lock
